<?php
// ───────────────────────────────────────
// DI containers
// ───────────────────────────────────────
$routeDiContainer = new routeDiContainer(
	$board,
	$config,
	$moduleEngine,
	$templateEngine,
	$adminTemplateEngine,
	$overboard,
	$adminPageRenderer,
	$softErrorHandler,
	$boardRepository,
	$boardService,
	$postRepository,
	$postService,
	$threadRepository,
	$threadService,
	$accountRepository,
	$accountService,
	$actionLoggerRepository,
	$actionLoggerService,
	$adminLoginController,
	$staffAccountFromSession,
	$postValidator,
	$transactionManager,
	$postRedirectService,
	$databaseConnection,
	$boardPathService,
	$visibleBoards,
	$boardList,
	$quoteLinkRepository,
	$quoteLinkService,
	$deletedPostsService,
	$postPolicy,
	$threadApi,
	$boardApi,
	$fileService,
);
