<?php
/**
 * Config schema for the emotes module (namespace: modules.emotes.*).
 * Read via $this->getModuleConfig('KEY'). Folds into the "Content & formatting" editor group.
 */

require_once __DIR__ . '/../../global/configs/_fieldTypes.php';

use function Kokonotsuba\config\fields\{arrayField};

return [
	'_group'  => 'Content & formatting',
	'_module' => 'Emotes',

	'KAOMOJI' => arrayField('Kaomoji', [
  'ヽ(´ー｀)ノ' => '[kao]ヽ(´ー｀)ノ[/kao]',
  '(;´Д`)' => '[kao](;´Д`)[/kao]',
  'ヽ(´∇`)ノ' => '[kao]ヽ(´∇`)ノ[/kao]',
  '(´人｀)' => '[kao](´人｀)[/kao]',
  '(＾Д^)' => '[kao](＾Д^)[/kao]',
  '(´ー`)' => '[kao](´ー`)[/kao]',
  '（ ´,_ゝ`）' => '[kao]（ ´,_ゝ`）[/kao]',
  '(´～`)' => '[kao](´～`)[/kao]',
  '(;ﾟДﾟ)' => '[kao](;ﾟДﾟ)[/kao]',
  '(;ﾟ∀ﾟ)' => '[kao](;ﾟ∀ﾟ)[/kao]',
  '┐(ﾟ～ﾟ)┌' => '[kao]┐(ﾟ～ﾟ)┌[/kao]',
  'ヽ(`Д´)ノ' => '[kao]ヽ(`Д´)ノ[/kao]',
  '( ´ω`)' => '[kao]( ´ω`)[/kao]',
  '(ﾟー｀)' => '[kao](ﾟー｀)[/kao]',
  '(・∀・)' => '[kao](・∀・)[/kao]',
  '（⌒∇⌒ゞ）' => '[kao]（⌒∇⌒ゞ）[/kao]',
  '(ﾟ血ﾟ#)' => '[kao](ﾟ血ﾟ#)[/kao]',
  '(ﾟｰﾟ)' => '[kao](ﾟｰﾟ)[/kao]',
  '(´￢`)' => '[kao](´￢`)[/kao]',
  '(´π｀)' => '[kao](´π｀)[/kao]',
  'ヽ(ﾟρﾟ)ノ' => '[kao]ヽ(ﾟρﾟ)ノ[/kao]',
  'Σ(;ﾟДﾟ)' => '[kao]Σ(;ﾟДﾟ)[/kao]',
  'Σ(ﾟдﾟ|||)' => '[kao]Σ(ﾟдﾟ|||)[/kao]',
  'ｷﾀ━━━(・∀・)━━━!!' => '[kao]ｷﾀ━━━(・∀・)━━━!![/kao]',
], 'JSON object of display text => value inserted into the comment.'),
	'EMOTES' => arrayField('Emotes', [
  'angry' => 'emo-yotsuba-angry.gif',
  'astonish' => 'emo-yotsuba-astonish.gif',
  'biggrin' => 'emo-yotsuba-biggrin.gif',
  'closed-eyes' => 'emo-yotsuba-closed-eyes.gif',
  'closed-eyes2' => 'emo-yotsuba-closed-eyes2.gif',
  'cool' => 'emo-yotsuba-cool.gif',
  'cry' => 'emo-yotsuba-cry.gif',
  'dark' => 'emo-yotsuba-dark.gif',
  'dizzy' => 'emo-yotsuba-dizzy.gif',
  'drool' => 'emo-yotsuba-drool.gif',
  'glare' => 'emo-yotsuba-glare.gif',
  'glare1' => 'emo-yotsuba-glare-01.gif',
  'glare2' => 'emo-yotsuba-glare-02.gif',
  'happy' => 'emo-yotsuba-happy.gif',
  'huh' => 'emo-yotsuba-huh.gif',
  'nosebleed' => 'emo-yotsuba-nosebleed.gif',
  'nyaoo' => 'emo-yotsuba-nyaoo.gif',
  'nyaoo2' => 'emo-yotsuba-nyaoo2.gif',
  'nyaoo-closedeyes' => 'emo-yotsuba-nyaoo-closedeyes.gif',
  'ph34r' => 'emo-yotsuba-ph34r.gif',
  'ninja' => 'emo-yotsuba-ph34r.gif',
  'rolleyes' => 'emo-yotsuba-rolleyes.gif',
  'rollseyes' => 'emo-yotsuba-rolleyes.gif',
  'sad' => 'emo-yotsuba-sad.gif',
  'smile' => 'emo-yotsuba-smile.gif',
  'sweat' => 'emo-yotsuba-sweat.gif',
  'sweat2' => 'emo-yotsuba-sweat2.gif',
  'sweat3' => 'emo-yotsuba-sweat3.gif',
  'tongue' => 'emo-yotsuba-tongue.gif',
  'unsure' => 'emo-yotsuba-unsure.gif',
  'wink' => 'emo-yotsuba-wink.gif',
  'x3' => 'emo-yotsuba-x3.gif',
  'xd' => 'emo-yotsuba-xd.gif',
  'xp' => 'emo-yotsuba-xp.gif',
  'love' => 'emo-yotsuba-heart.gif',
  'blush' => 'emo-yotsuba-blush3.gif',
  'mask' => 'emo-yotsuba-mask.gif',
  'emo' => 'emo.gif',
  'lolico' => 'emo-yotsuba-lolico.gif',
  'kuz' => 'emo-yotsuba-tomo.gif',
  'dance' => 'heyuri-dance.gif',
  'dance2' => 'heyuri-dance-pantsu.gif',
  'nigra' => 'nigra.gif',
  'sage' => 'sage.gif',
  'longcat' => 'longcat.gif',
  'tacgnol' => 'tacgnol.gif',
  'mona2' => 'mona2.gif',
  'nida' => 'nida.gif',
  'iyahoo' => 'iyahoo.gif',
  'banana' => 'banana.gif',
  'onigiri' => 'onigiri.gif',
  'shii' => 'anime_shii01.gif',
  'saitama' => 'anime_saitama05.gif',
  'foruda' => 'foruda.gif',
  'nagato' => 'nagato.gif',
  'kuma6' => 'kuma6.gif',
  'waha' => 'waha.gif',
  'hokke' => 'hokke.gif',
  'af2' => 'af2.gif',
  'pata' => 'u_pata.gif',
  'depression' => 'u_sasu.gif',
  'saitama2' => 'anime_saitama06.gif',
  'monapc' => 'anime_miruna_pc.gif',
  'purin' => 'purin.gif',
  'ranta' => 'anime_imanouchi04.gif',
], 'JSON object of emote name => image filename (from static/image/emotes/).'),
];
