<?php
/**
 * Config schema for the nameRandomizer module (namespace: modules.nameRandomizer.*).
 * Read via $this->getModuleConfig('KEY'). Folds into the "Content & formatting" editor group.
 */

require_once __DIR__ . '/../../configs/_fieldTypes.php';

use function Kokonotsuba\config\fields\{arrayField, intField};

return [
	'_group'  => 'Content & formatting',
	'_module' => 'Name randomizer',

	'NAME_RANDOMIZER_TTL' => intField('Name randomizer TTL (s)', 43200, 'config_desc_modules.nameRandomizer.NAME_RANDOMIZER_TTL'),
	'NAME_RANDOMIZER_NAMES' => arrayField('Name randomizer pool', [
  0 => 'Shota Liberation Army',
  1 => 'Nyuu',
  2 => 'Nyo',
  3 => 'Ootani-san',
  4 => 'Onsokumaru',
  5 => 'Shinobu',
  6 => 'Sasuke',
  7 => 'Madarame',
  8 => 'oono',
  9 => 'Saki',
  10 => 'Saya',
  11 => 'Rabi-en-rose',
  12 => 'Momoha',
  13 => 'Hitomi Tanaka',
  14 => 'Gokiburu',
  15 => 'Porkchop',
  16 => '1931, the king of /b/',
  17 => 'Six figures',
  18 => 'Tululoo',
  19 => 'Puchippy',
  20 => 'Alice',
  21 => 'Roach',
  22 => 'Meta44',
  23 => 'Spemwaxx',
  24 => 'Iruyeh-tan',
  25 => 'Lolicious',
  26 => 'Chiyo Penguin',
  27 => 'The Balancer',
  28 => 'Fortune God',
  29 => 'Vomit Snake',
  30 => '|ω・`)じー',
  31 => 'Richard Lewis',
  32 => 'Spam-kun',
  33 => 'Wormhole-kun',
  34 => 'x7m0d',
  35 => 'Fall in love with ME',
  36 => 'Imouto-san',
  37 => 'Umaru',
  38 => 'Onii-chan',
  39 => 'Kimura-sensei',
  40 => 'Osaka',
  41 => 'Sakaki-san',
  42 => 'Mint',
  43 => 'Milfeulle',
  44 => 'Forte',
  45 => 'Banira',
  46 => 'Matsuri',
  47 => 'Miu',
  48 => 'Nobue-onee-chan',
  49 => 'Sasazuka',
  50 => 'Ana',
  51 => 'ZA PEIPA',
  52 => 'MISTER GENTLEMEN',
  53 => 'Miss Deepu',
  54 => 'UUUUUUU~',
  55 => 'Jun',
  56 => 'Suiseiseki',
  57 => 'Souseiseki',
  58 => 'Kirakishou',
  59 => 'Suigintou',
  60 => 'Nori (talking boob)',
  61 => 'Rei',
  62 => 'Ayanami',
  63 => 'Asuka',
  64 => 'Gendo',
  65 => 'Fuyutsuki',
  66 => 'Ikari Yui',
  67 => 'Adam',
  68 => 'Lilith',
  69 => 'Puchiko',
  70 => 'Dejiko',
  71 => 'Hikaru Usada',
  72 => 'Manager-san',
  73 => 'Gema',
  74 => 'Abarenbou',
  75 => 'Remilia Scarlet',
  76 => 'Patchouli',
  77 => 'Marisa',
  78 => 'Reimu',
  79 => 'Tenshi',
  80 => 'Aya',
  81 => 'Chris Handson',
  82 => 'Hanekawa',
  83 => 'Mararagi',
  84 => 'Biscuit-tan',
  85 => 'Habanero-tan',
  86 => 'hiroyuki',
  87 => 'Grimm',
], 'config_desc_modules.nameRandomizer.NAME_RANDOMIZER_NAMES'),
];
