<?php

namespace Kokonotsuba\Modules\notes;

use Kokonotsuba\database\transactionManager;

/** Service for creating, editing, and deleting staff notes on posts. */
class noteService {
	public function __construct(
		private noteRepository $noteRepository,
		private transactionManager $transactionManager
	) {}

	/**
	 * Add a note to a post and return the new note's ID.
	 *
	 * @param int    $postUid   UID of the post to annotate.
	 * @param string $noteText  Note content.
	 * @param int    $accountId ID of the staff account creating the note.
	 * @return int|null|false The new note ID, or null/false on failure.
	 */
	public function addNote(
		int $postUid, 
		string $noteText, 
		int $accountId
	): false|null|int {
		// init note id variable so we can alter and return it
		$noteId = null;

		// wrap note insert call in transaction just in case
		$this->transactionManager->run(function() use (
			$postUid, 
			$noteText, 
			$accountId,
			&$noteId
		) {
				$this->noteRepository->insertNote($postUid, $noteText, $accountId);
				$noteId = $this->noteRepository->getLastInsertId();
			});
		
		// return the note ID of the newly inserted note, or null if insertion failed
		return $noteId;
	}

	/**
	 * Update the text of an existing note.
	 *
	 * @param int    $noteId  Note primary key.
	 * @param string $newText Replacement text.
	 * @return void
	 */
	public function editNote(int $noteId, string $newText): void {
		// wrap note update call in transaction just in case
		$this->transactionManager->run(function() use ($noteId, $newText) {
			$this->noteRepository->editNote($noteId, $newText);
		});
	}
	
	/**
	 * Check whether the given note belongs to the given account.
	 *
	 * @param int $accountId Account ID.
	 * @param int $noteId    Note ID to check.
	 * @return bool True if the account owns the note.
	 */
	public function noteOwnedByAccount(int $accountId, int $noteId): bool {
		return $this->noteRepository->noteOwnedByAccount($accountId, $noteId);
	}

	/**
	 * Delete a note by its primary key.
	 *
	 * @param int $noteId Note primary key.
	 * @return void
	 */
	public function deleteNote(int $noteId): void {
		// wrap note delete call in transaction just in case
		$this->transactionManager->run(function() use ($noteId) {
			$this->noteRepository->deleteNote($noteId);
		});
	}

	/**
	 * Fetch a note by its primary key.
	 *
	 * @param int $noteId Note primary key.
	 * @return array|false Associative row array, or false if not found.
	 */
	public function getNoteById(int $noteId): false|array {
		return $this->noteRepository->getNoteById($noteId);
	}

	/**
	 * Return the ID generated by the most recent INSERT.
	 *
	 * @return int Last insert ID.
	 */
	public function getLastInsertId(): int {
		return $this->noteRepository->getLastInsertId();
	}
}