<?php

namespace Kokonotsuba\Modules\notes;

use Kokonotsuba\database\baseRepository;
use Kokonotsuba\database\databaseConnection;

/**
 * Repository for staff notes attached to individual posts.
 *
 * Table structure
 * id INT AUTO_INCREMENT PRIMARY KEY,
 * post_uid INT NOT NULL,
 * note_submitted TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 * added_by INT NULL,
 * note_text TEXT NOT NULL,
 */

class noteRepository extends baseRepository {
	public function __construct(
		databaseConnection $databaseConnection,
		string $noteTable
	) {
		parent::__construct($databaseConnection, $noteTable);
	}

	/**
	 * Insert a new note for the given post.
	 *
	 * @param int    $postUid   UID of the post the note belongs to.
	 * @param string $noteText  Note content.
	 * @param int    $accountId ID of the staff account adding the note.
	 * @return void
	 */
	public function insertNote(
		int $postUid, 
		string $noteText, 
		int $accountId
	): void {
		$this->insert([
			'post_uid' => $postUid,
			'note_text' => $noteText,
			'added_by' => $accountId,
		]);
	}

	/**
	 * Check whether the given note belongs to the given account.
	 *
	 * @param int $accountId Account ID to check ownership for.
	 * @param int $noteId    Note ID to verify.
	 * @return bool True if the note is owned by the account.
	 */
	public function noteOwnedByAccount(int $accountId, int $noteId): bool {
		$query = "SELECT 1 FROM {$this->table} WHERE id = :note_id AND added_by = :account_id";
		return $this->queryValue($query, [':note_id' => $noteId, ':account_id' => $accountId]) === 1;
	}

	/**
	 * Delete a note by its primary key.
	 *
	 * @param int $noteId Note primary key.
	 * @return void
	 */
	public function deleteNote(int $noteId): void {
		$this->deleteWhere('id', $noteId);
	}

	/**
	 * Update the text of an existing note.
	 *
	 * @param int    $noteId  Note primary key.
	 * @param string $newText Replacement text.
	 * @return void
	 */
	public function editNote(int $noteId, string $newText): void {
		$this->updateWhere(['note_text' => $newText], 'id', $noteId);
	}

	/**
	 * Fetch a note by its primary key.
	 *
	 * @param int $noteId Note primary key.
	 * @return array|false Associative row array, or false if not found.
	 */
	public function getNoteById(int $noteId): false|array {
		return $this->findBy('id', $noteId);
	}

	/**
	 * Return the ID generated by the most recent INSERT.
	 *
	 * @return int|false Last insert ID, or false if unavailable.
	 */
	public function getLastInsertId(): false|int {
		return $this->lastInsertId();
	}
}