<?php
//template convenience library
function bindReplyValuesToTemplate(IBoard $board, 
    array $config, 
    int $post_uid, 
    int $no, 
    int $resto, 
    bool $postPositionEnabled,
    int $post_position,
    string $sub, 
    string $name, 
    string $now, 
    string $category, 
    string $quoteButton, 
    string $imgBar, 
    string $imgSrc, 
    string $warnBeKill, 
    string $comment, 
    string $postFormExtra) 
{
    return [
        '{$BOARD_URL}' => $board->getBoardURL(),
        '{$BOARD_UID}' => $board->getBoardUID(),
        '{$BOARD_IDENTIFIER}' => $board->getBoardIdentifier(),
        '{$POST_UID}' => $post_uid,
        '{$NO}' => $no,
        '{$RESTO}' => $resto, 
        '{$POST_POSITION_ENABLED}' => $postPositionEnabled,
        '{$POST_POSITION}' => $post_position,
        '{$SUB}' => $sub, 
        '{$NAME}' => $name, 
        '{$NOW}' => $now, 
        '{$CATEGORY}' => $category, 
        '{$QUOTEBTN}' => $quoteButton, 
        '{$IMG_BAR}' => $imgBar,
        '{$IMG_SRC}' => $imgSrc,
        '{$WARN_BEKILL}' => $warnBeKill, 
        '{$NAME_TEXT}' => _T('post_name'), 
        '{$CATEGORY_TEXT}' => _T('post_category'), 
        '{$SELF}' => $config['PHP_SELF'],
        '{$COM}' => $comment, 
        '{$POSTINFO_EXTRA}' => $postFormExtra,
        '{$IS_THREAD}' => false
    ];
}

function bindOPValuesToTemplate(IBoard $board, 
    array $config, 
    int $post_uid, 
    int $no, 
    string $sub, 
    string $name, 
    string $now, 
    string $category, 
    string $quoteButton, 
    string $replyButton, 
    string $imgBar, 
    string $imgSrc, 
    string $fileName, 
    string $fileSize, 
    int $imgWidth, 
    int $imgHeight, 
    string $fileLink, 
    int $numberOfReplies, 
    string $warnOld, 
    string $warnBeKill, 
    string $warnEndReply, 
    string $warnHidePost, 
    string $comment, 
    string $postFormExtra) 
{
    return [
        '{$BOARD_URL}' => $board->getBoardURL(),
        '{$BOARD_UID}' => $board->getBoardUID(),
        '{$BOARD_IDENTIFIER}' => $board->getBoardIdentifier(),
        '{$POST_UID}' => $post_uid,
        '{$NO}' => $no, 
        '{$RESTO}' => $no, 
        '{$SUB}' => $sub, 
        '{$NAME}' => $name, 
        '{$NOW}' => $now, 
        '{$CATEGORY}' => $category, 
        '{$QUOTEBTN}' => $quoteButton, 
        '{$REPLYBTN}' => $replyButton, 
        '{$IMG_BAR}' => $imgBar, 
        '{$IMG_SRC}' => $imgSrc, 
        '{$FILE_NAME}' => $fileName,
        '{$ESCAPED_FILE_NAME}' => htmlspecialchars($fileName),
        '{$FILE_SIZE}' => $fileSize,
        '{$FILE_WIDTH}' => $imgWidth,
        '{$FILE_HEIGHT}' => $imgHeight,
        '{$FILE_LINK}' => $fileLink,
        '{$REPLYNUM}' => $numberOfReplies - 1,
        '{$WARN_OLD}' => $warnOld, 
        '{$WARN_BEKILL}' => $warnBeKill,
        '{$WARN_ENDREPLY}' => $warnEndReply, 
        '{$WARN_HIDEPOST}' => $warnHidePost, 
        '{$NAME_TEXT}' => _T('post_name'), 
        '{$CATEGORY_TEXT}' => _T('post_category'), 
        '{$SELF}' => $config['PHP_SELF'], 
        '{$COM}' => $comment, 
        '{$POSTINFO_EXTRA}' => $postFormExtra,
        '{$IS_THREAD}' => true,
    ];
}
