<?php
/**
 * Content transforms: BBCode, word filters, emotes, image metadata, country flags,
 * name randomizer and the segregator. Defaults preserve the historical board defaults.
 */

$support = static fn(string $label, bool $default): array => [
	'default' => $default,
	'type'    => 'bool',
	'label'   => $label,
];

return [
	'_group' => 'Content & formatting',

	// image metadata
	'ModuleSettings.EXIF_DATA_VIEWER' => ['default' => false, 'type' => 'bool', 'label' => 'EXIF data viewer', 'desc' => 'Show an EXIF data viewer for images.'],
	'ModuleSettings.IMG_OPS'          => ['default' => true,  'type' => 'bool', 'label' => 'ImgOps portal', 'desc' => 'ImgOps reverse-image-search portal.'],
	'ModuleSettings.IQDB'             => ['default' => false, 'type' => 'bool', 'label' => 'IQDB portal', 'desc' => 'IQDB reverse-image-search portal.'],
	'ModuleSettings.SWFCHAN'          => ['default' => true,  'type' => 'bool', 'label' => 'SWFchan archive', 'desc' => 'SWFchan archive link.'],

	// country flags
	'ModuleSettings.FLAG_MODE' => ['default' => 1, 'type' => 'int', 'label' => 'Country flag mode', 'desc' => '1 = hide flags on posts with "flag" in the email field, 2 = show them.'],

	// name randomizer
	'ModuleSettings.NAME_RANDOMIZER_TTL' => ['default' => 43200, 'type' => 'int', 'label' => 'Name randomizer TTL (s)', 'desc' => 'How long a randomized name persists, in seconds.'],

	// segregator
	'ModuleSettings.SEGREGATOR_SUB_DOMAIN'   => ['default' => '', 'type' => 'string', 'label' => 'Segregator subdomain', 'desc' => 'Subdomain prefix prepended to the file host (empty = disabled).'],
	'ModuleSettings.SEGREGATOR_COOKIE_NAME'  => ['default' => 'viewAllContent', 'type' => 'string', 'label' => 'Segregator cookie name', 'desc' => 'Name of the access cookie checked by nginx.'],
	'ModuleSettings.SEGREGATOR_COOKIE_DOMAIN'=> ['default' => '', 'type' => 'string', 'label' => 'Segregator cookie domain', 'desc' => 'Cookie domain scope (empty = current host only).'],

	// BBCode support flags
	'ModuleSettings.supportBold'          => $support('BBCode: bold', true),
	'ModuleSettings.supportSpoiler'       => $support('BBCode: spoiler', true),
	'ModuleSettings.supportStrikeThrough' => $support('BBCode: strikethrough', true),
	'ModuleSettings.supportHeading'       => $support('BBCode: heading', true),
	'ModuleSettings.supportCode'          => $support('BBCode: code', true),
	'ModuleSettings.supportCodeBlocks'    => $support('BBCode: code blocks', true),
	'ModuleSettings.supportItalic'        => $support('BBCode: italic', true),
	'ModuleSettings.supportUnderline'     => $support('BBCode: underline', true),
	'ModuleSettings.supportParagraph'     => $support('BBCode: paragraph', true),
	'ModuleSettings.supportSw'            => $support('BBCode: strange-world AA', true),
	'ModuleSettings.supportColor'         => $support('BBCode: color', true),
	'ModuleSettings.supportColorBg'       => $support('BBCode: background color', true),
	'ModuleSettings.supportNeon'          => $support('BBCode: neon', true),
	'ModuleSettings.supportTextShadow'    => $support('BBCode: text shadow', true),
	'ModuleSettings.supportPartybus'      => $support('BBCode: partybus', true),
	'ModuleSettings.supportEcho'          => $support('BBCode: echo', true),
	'ModuleSettings.supportFontSize'      => $support('BBCode: font size', true),
	'ModuleSettings.supportPre'           => $support('BBCode: pre', true),
	'ModuleSettings.supportQuote'         => $support('BBCode: quote', true),
	'ModuleSettings.supportRuby'          => $support('BBCode: ruby', true),
	'ModuleSettings.supportURL'           => $support('BBCode: URL', false),
	'ModuleSettings.supportEmail'         => $support('BBCode: email', false),
	'ModuleSettings.supportImg'           => $support('BBCode: img', false),
	'ModuleSettings.supportScroll'        => $support('BBCode: scroll', true),
	'ModuleSettings.supportKao'           => $support('BBCode: kao', true),

	// word filters
	'ModuleSettings.FILTERS' => [
		'default' => [
			'/\b(rabi-en-rose|rabi~en~rose)\b/i' => '<span class="rabienrose">Rabi~en~Rose</span>',
			'/\b(newfag)\b/i' => 'n00b like me',
			'/\b(newfags)\b/i' => 'n00bs like me',
			'/\b(heyuri★cgi)\b/i' => '<a href="https://wiki.heyuri.net/index.php?title=Heyuri%E2%98%85CGI">Heyuri★CGI</a>',
			'/\b(heyuri cgi)\b/i' => '<a href="https://wiki.heyuri.net/index.php?title=Heyuri%E2%98%85CGI">Heyuri★CGI</a>',
			'/\b(chat@heyuri)\b/i' => '<a href="https://cgi.heyuri.net/chat/">Chat@Heyuri</a>',
			'/\b(polls@heyuri)\b/i' => '<a href="https://cgi.heyuri.net/vote2/">Polls@Heyuri</a>',
			'/\b(dating@heyuri)\b/i' => '<a href="https://cgi.heyuri.net/dating/">Dating@Heyuri</a>',
			'/\b(uploader@heyuri)\b/i' => '<a href="https://up.heyuri.net/">Uploader@Heyuri</a>',
			'/@party 2/i' => '<a href="https://cgi.heyuri.net/party2/">@Party II</a>',
			'/@party ii/i' => '<a href="https://cgi.heyuri.net/party2/">@Party II</a>',
			'/\b(ayashii world)\b/i' => '<a href="https://wiki.heyuri.net/index.php?title=Ayashii_World">Ayashii World</a>',
			'/\b(partybus)\b/i' => '<span class="partybus"><span class="partybusColor1">p</span><span class="partybusColor2">a</span><span class="partybusColor3">r</span><span class="partybusColor4">t</span><span class="partybusColor5">y</span><span class="partybusColor6">b</span><span class="partybusColor7">u</span><span class="partybusColor8">s</span></span>',
			'/\b(boku)\b/i' => '<span class="boku" title="AGE OF DESU IS OVAR, WE BOKU NOW"><span class="bokuGreen">B</span><span class="bokuRed">O</span><span class="bokuGreen">K</span><span class="bokuRed">U</span></span>',
		],
		'type'  => 'array',
		'label' => 'Word filters',
		'desc'  => 'JSON object of regex pattern => replacement HTML.',
	],

	// emotes (must exist in static/image/emotes/)
	'ModuleSettings.EMOTES' => [
		'default' => [
			'angry'		=>'emo-yotsuba-angry.gif',
			'astonish'	=>'emo-yotsuba-astonish.gif',
			'biggrin'	=>'emo-yotsuba-biggrin.gif',
			'closed-eyes'=>'emo-yotsuba-closed-eyes.gif',
			'closed-eyes2'=>'emo-yotsuba-closed-eyes2.gif',
			'cool'		=> 'emo-yotsuba-cool.gif',
			'cry'		=> 'emo-yotsuba-cry.gif',
			'dark'		=>'emo-yotsuba-dark.gif',
			'dizzy'		=>'emo-yotsuba-dizzy.gif',
			'drool'		=>'emo-yotsuba-drool.gif',
			'glare'		=>'emo-yotsuba-glare.gif',
			'glare1'	=>'emo-yotsuba-glare-01.gif',
			'glare2'	=>'emo-yotsuba-glare-02.gif',
			'happy'		=>'emo-yotsuba-happy.gif',
			'huh'		=>'emo-yotsuba-huh.gif',
			'nosebleed'	=>'emo-yotsuba-nosebleed.gif',
			'nyaoo'		=>'emo-yotsuba-nyaoo.gif',
			'nyaoo2'	=>'emo-yotsuba-nyaoo2.gif',
			'nyaoo-closedeyes'	=>'emo-yotsuba-nyaoo-closedeyes.gif',
			'ph34r'		=>'emo-yotsuba-ph34r.gif',
			'ninja'		=>'emo-yotsuba-ph34r.gif',
			'rolleyes'	=>'emo-yotsuba-rolleyes.gif',
			'rollseyes'	=>'emo-yotsuba-rolleyes.gif',
			'sad'		=>'emo-yotsuba-sad.gif',
			'smile'		=>'emo-yotsuba-smile.gif',
			'sweat'		=>'emo-yotsuba-sweat.gif',
			'sweat2'	=>'emo-yotsuba-sweat2.gif',
			'sweat3'	=>'emo-yotsuba-sweat3.gif',
			'tongue'	=>'emo-yotsuba-tongue.gif',
			'unsure'	=>'emo-yotsuba-unsure.gif',
			'wink'		=>'emo-yotsuba-wink.gif',
			'x3'		=>'emo-yotsuba-x3.gif',
			'xd'		=>'emo-yotsuba-xd.gif',
			'xp'		=>'emo-yotsuba-xp.gif',
			'love'		=>'emo-yotsuba-heart.gif',
			'blush'		=>'emo-yotsuba-blush3.gif',
			'mask'		=>'emo-yotsuba-mask.gif',
			'emo'		=>'emo.gif',
			'lolico'	=>'emo-yotsuba-lolico.gif',
			'kuz'		=>'emo-yotsuba-tomo.gif',
			'dance'		=>'heyuri-dance.gif',
			'dance2'	=>'heyuri-dance-pantsu.gif',
			'nigra'		=>'nigra.gif',
			'sage'		=>'sage.gif',
			'longcat'	=>'longcat.gif',
			'tacgnol'	=>'tacgnol.gif',
			'mona2'		=>'mona2.gif',
			'nida'		=>'nida.gif',
			'iyahoo'	=>'iyahoo.gif',
			'banana'	=>'banana.gif',
			'onigiri'	=>'onigiri.gif',
			'shii'		=>'anime_shii01.gif',
			'saitama'	=>'anime_saitama05.gif',
			'foruda'	=>'foruda.gif',
			'nagato'	=>'nagato.gif',
			'kuma6'		=>'kuma6.gif',
			'waha'		=>'waha.gif',
			'hokke'		=>'hokke.gif',
			'af2'		=>'af2.gif',
			'pata'		=>'u_pata.gif',
			'depression'=>'u_sasu.gif',
			'saitama2'	=>'anime_saitama06.gif',
			'monapc'	=>'anime_miruna_pc.gif',
			'purin'		=>'purin.gif',
			'ranta'		=>'anime_imanouchi04.gif',
		],
		'type'  => 'array',
		'label' => 'Emotes',
		'desc'  => 'JSON object of emote name => image filename (from static/image/emotes/).',
	],

	// name randomizer pool
	'ModuleSettings.NAME_RANDOMIZER_NAMES' => [
		'default' => [
			'Shota Liberation Army', 'Nyuu', 'Nyo', 'Ootani-san', 'Onsokumaru', 'Shinobu', 'Sasuke',
			'Madarame', 'oono', 'Saki', 'Saya', 'Rabi-en-rose', 'Momoha', 'Hitomi Tanaka', 'Gokiburu',
			'Porkchop', '1931, the king of /b/', 'Six figures', 'Tululoo', 'Puchippy', 'Alice', 'Roach',
			'Meta44', 'Spemwaxx', 'Iruyeh-tan', 'Lolicious', 'Chiyo Penguin', 'The Balancer', 'Fortune God',
			'Vomit Snake', '|ω・`)じー', 'Richard Lewis', 'Spam-kun', 'Wormhole-kun', 'x7m0d',
			'Fall in love with ME', 'Imouto-san', 'Umaru', 'Onii-chan', 'Kimura-sensei', 'Osaka',
			'Sakaki-san', 'Mint', 'Milfeulle', 'Forte', 'Banira', 'Matsuri', 'Miu', 'Nobue-onee-chan',
			'Sasazuka', 'Ana', 'ZA PEIPA', 'MISTER GENTLEMEN', 'Miss Deepu', 'UUUUUUU~', 'Jun', 'Suiseiseki',
			'Souseiseki', 'Kirakishou', 'Suigintou', 'Nori (talking boob)', 'Rei', 'Ayanami', 'Asuka',
			'Gendo', 'Fuyutsuki', 'Ikari Yui', 'Adam', 'Lilith', 'Puchiko', 'Dejiko', 'Hikaru Usada',
			'Manager-san', 'Gema', 'Abarenbou', 'Remilia Scarlet', 'Patchouli', 'Marisa', 'Reimu', 'Tenshi',
			'Aya', 'Chris Handson', 'Hanekawa', 'Mararagi', 'Biscuit-tan', 'Habanero-tan', 'hiroyuki', 'Grimm',
		],
		'type'  => 'array',
		'label' => 'Name randomizer pool',
		'desc'  => 'JSON array of names picked at random when the name randomizer is enabled.',
	],
];
